name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MIX_ENV: test
      DATABASE_URL: ecto://postgres:postgres@localhost/test_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: '1.14'
          otp-version: '25.3' # ✅ Updated to a supported OTP version
          version-type: strict

      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: mix-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            mix-${{ runner.os }}-

      - name: Install dependencies
        run: mix deps.get

      - name: Setup database
        run: |
          mix ecto.create
          mix ecto.migrate

      - name: Run tests
        run: mix test

      # Uncomment only if you have releases configured
      # - name: Build release
      #   run: MIX_ENV=prod mix release

      - name: Notify success
        if: success()
        run: echo "✅ Build and tests passed!"

      - name: Notify failure
        if: failure()
        run: echo "❌ Build or tests failed!"
